-- Punto 1
SELECT ID_MATERIALCONSTRUCCION AS ID, NOMBRE_MATERIAL  AS NOMBRE, PRECIO_UNIDAD  AS PRECIO
FROM MATERIALCONSTRUCCION
WHERE IMPORTADO = 'Si'
ORDER BY NOMBRE_MATERIAL;

-- Punto 2
SELECT P.ID_PROYECTO AS ID, P.CONSTRUCTORA, P.CIUDAD, P.CLASIFICACION, T.ESTRATO, L.NOMBRE||' '||L.PRIMER_APELLIDO||' '||L.SEGUNDO_APELLIDO AS LIDER
FROM PROYECTO P 
JOIN TIPO T ON (P.ID_TIPO = T.ID_TIPO)
JOIN LIDER L ON (P.ID_LIDER = L.ID_LIDER)
WHERE P.BANCO_VINCULADO = 'Conavi'
ORDER BY FECHA_INICIO DESC, CIUDAD, CONSTRUCTORA;

-- Punto 3
SELECT CIUDAD, CLASIFICACION, COUNT(*) TOTAL, MIN(FECHA_INICIO) VIEJO, MAX(FECHA_INICIO) RECIENTE
FROM PROYECTO P 
WHERE CLASIFICACION NOT IN ('Casa Campestre', 'Condominio')
GROUP BY CIUDAD , CLASIFICACION
ORDER BY CIUDAD , CLASIFICACION;

-- Punto 4
SELECT P.ID_PROYECTO, SUM(C.CANTIDAD * MC.PRECIO_UNIDAD) AS VALOR
FROM PROYECTO P 
JOIN COMPRA C ON (P.ID_PROYECTO = C.ID_PROYECTO)
JOIN MATERIALCONSTRUCCION MC ON (C.ID_MATERIALCONSTRUCCION = MC.ID_MATERIALCONSTRUCCION)
WHERE C.PAGADO = 'No'
GROUP BY P.ID_PROYECTO
HAVING SUM(C.CANTIDAD * MC.PRECIO_UNIDAD) > 50000
ORDER BY VALOR DESC;

-- Punto 5
SELECT L.NOMBRE ||' '||L.PRIMER_APELLIDO ||' '||L.SEGUNDO_APELLIDO AS LIDER, SUM(C.CANTIDAD * MC.PRECIO_UNIDAD) AS VALOR
FROM LIDER L
JOIN PROYECTO P ON (P.ID_LIDER = L.ID_LIDER)
JOIN COMPRA C ON (P.ID_PROYECTO = C.ID_PROYECTO)
JOIN MATERIALCONSTRUCCION MC ON (C.ID_MATERIALCONSTRUCCION = MC.ID_MATERIALCONSTRUCCION)
GROUP BY L.NOMBRE ||' '||L.PRIMER_APELLIDO ||' '||L.SEGUNDO_APELLIDO
ORDER BY VALOR DESC
LIMIT 10;